
# Site settings
title: Benjamin Moran
email: benjamin.moran@uon.edu.au
description: >
  An online space for my Honours project.
github_username:  benneaux
theme: jekyll-theme-cayman
timezone: Australia/Sydney
# Build settings
markdown: kramdown
