
# Site settings
title: Benjamin Moran
email: benjamin.moran@uon.edu.au
description: >
  An online space for my Honours project.
github_username:  benneaux
theme: jekyll-theme-cayman
timezone: Australia/Sydney
# Build settings
markdown: kramdown

# source:       .
# destination:  ./_site
# plugins_dir:  _plugins
# layouts_dir:  _layouts
# data_dir:     _data
# includes_dir: _includes
# collections:
#  posts:
#    output:   true  
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
    
