---
title: "Honours Meeting"
author: "Benjamin Moran"
date: "5 May 2017"
output: html_document
---

```{r setup, include=FALSE}
library(astsa)
library(knitr)
library(ggplot2)
library(tidyverse)
library(forecast)
library(sweep)
library(timekit)
opts_chunk$set(collapse = TRUE, fig.align="center")
opts_chunk$set(cache = TRUE, echo = FALSE)
```

```{r data, include=FALSE}
fludata <- read.csv("Project/Data/fludata3.csv", header=TRUE)
UnVacc <- fludata$ILI_Unvaccinated
pr.iUnVacc <- which.min(UnVacc); UnVacc[pr.iUnVacc]
UnVacc[pr.iUnVacc] <- {UnVacc[pr.iUnVacc-3] + 2*UnVacc[pr.iUnVacc-2] + 3*UnVacc[pr.iUnVacc-1] + 3*UnVacc[pr.iUnVacc+1] + 2*UnVacc[pr.iUnVacc+2] + UnVacc[pr.iUnVacc+3]}/12


Vaxx <- fludata$ILI_Vaccinated
pr.iVaxx <- which.min(Vaxx)
Vaxx[pr.iVaxx] <- {Vaxx[pr.iVaxx-3] + 2*Vaxx[pr.iVaxx-2] + 3*Vaxx[pr.iVaxx-1] + 3*Vaxx[pr.iVaxx+1] + 2*Vaxx[pr.iVaxx+2] + Vaxx[pr.iVaxx+3]}/12
```



```{r}
fit <- arima(Vaxx,c(3,0,0))
fit$coef
pwUnVacc <- stats::filter(UnVacc, filter = c(1,-fit$coef[1],-fit$coef[3]), sides = 1)
resVaxx <- fit$residuals
```

```{r}
Vaxx <- ts(Vaxx,start = 1, end = 115)
zVaxx <- ts.intersect(Vaxx, stats::lag(Vaxx, -1), stats::lag(Vaxx, -4))
UnVacc <- ts(UnVacc, start = 1, end = 115)
zUnVacc <-  ts.intersect(UnVacc, stats::lag(UnVacc, -1), stats::lag(UnVacc, -2))
fit3 <- arima(zUnVacc[3:103,1], xreg = cbind(zUnVacc[3:103,2], zUnVacc[3:103,3],zVaxx[1:101,2]))
newstuff <- cbind(zUnVacc[104:113,2], zUnVacc[104:113,3],zVaxx[102:111,2])
predictions <- ts(as.numeric(predict(fit3,newxreg = newstuff)$pred), start = 106)
plot(UnVacc[1:115], type = "l",col = "red") +
lines(predictions, type  = "l")

fcastfit3
fitar <- ets(fit3$residuals)
```

```{r}
VaxxNew <- ts(Vaxx[1:92], start = 1, end = 92)
UnVaccNew <- ts(UnVacc[1:92], start = 1, end = 92)
```

Use this model to predict 2016. Condider all from 2015; then all 2015 + first week of 2016.

#### Relative error

```{r relerror}
n.samp <- 23
end.ind <- length(UnVacc) - n.samp
fit3 <- lm(zUnVacc[3:end.ind,1] ~ zUnVacc[3:end.ind,2] + zUnVacc[3:end.ind,3] + zVaxx[3:end.ind,2])

predicted <- tbl_df(predict(fit3, newdata = data.frame(x = n.samp), se.fit = TRUE))

rel.error <- abs(UnVacc[(end.ind + 1):115]-predicted$fit)/UnVacc[(end.ind + 1):115]

rel.error2 <- data.frame(data=cbind(UnVacc[(end.ind + 1):115], predicted$fit, rel.error))
colnames(rel.error2) <- c("Actual", "Predicted", "Relative error")
rel.error3 <- rel.error2 %>%
  mutate(ID = 1:n()) %>%
  select(-`Relative error`) %>%
  gather(key = series, value = values, `Actual`, `Predicted`,-ID)

ggplot(data = rel.error3, aes(x = ID, y = values, group = series, colour = series)) + 
  geom_path() + 
  coord_cartesian(ylim = c(0,0.1))
# kable(rel.error2)
```

```{r plotpred}
plot.ts(UnVacc[1:end.ind], ylim=c(0, 0.06)) # Label title and axes
lines(c((end.ind + 1):115), as.numeric(predict(fit3,newdata = data.frame(x = n.samp)), col="red"))
test <- predict(fit3, new, interval = "prediction")
```
